
name: Runme

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        rangeIndex: ["1830 1835 1", "1830 1835 2", "1830 1835 3", "1830 1835 4", "1830 1835 5", "1835 1840 6", "1835 1840 7", "1835 1840 8", "1835 1840 9", "1835 1840 10", "1840 1845 11", "1840 1845 12", "1840 1845 13", "1840 1845 14", "1840 1845 15"]
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y libgbm1 
      - name: Run
        run: |
          node run.js ${{ matrix.rangeIndex }}
      - name: done
        run: exit
