

name: Runme

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        rangeIndex: ["630 635 1", "630 635 2", "630 635 3", "630 635 4", "630 635 5", "630 635 6", "630 635 7", "635 640 8", "635 640 9", "635 640 10", "635 640 11", "635 640 12", "635 640 13", "635 640 14", "640 645 15", "640 645 16", "640 645 17", "640 645 18", "640 645 19", "640 645 20", "640 645 21"]
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        uses: actions/setup-node@v4
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
        with:
          node-version: 18
      - name: Test Code
        uses: mujo-code/puppeteer-headful@16.6.0
        env:
          RANGE_INDEX: ${{ matrix.rangeIndex }}
          MY_DATA: ${{secrets.WK_U}} ${{secrets.WK_I}} ${{secrets.WK_S}} ${{secrets.BK_U}}
        with:
          args: |
            npm run start
      - name: done
        run: exit
