

name: Runme

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        rangeIndex: ["900 905 1", "900 905 2", "900 905 3", "900 905 4", "900 905 5", "900 905 6", "900 905 7", "905 910 8", "905 910 9", "905 910 10", "905 910 11", "905 910 12", "905 910 13", "905 910 14", "910 915 15", "910 915 16", "910 915 17", "910 915 18", "910 915 19", "910 915 20", "910 915 21"]
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        uses: actions/setup-node@v4
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
        with:
          node-version: 18
      - name: Test Code
        uses: mujo-code/puppeteer-headful@16.6.0
        env:
          RANGE_INDEX: ${{ matrix.rangeIndex }}
          MY_DATA: ${{secrets.WK_U}} ${{secrets.WK_I}} ${{secrets.WK_S}} ${{secrets.BK_U}}
        with:
          args: |
            npm run start
      - name: done
        run: exit
