

name: Runme

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        rangeIndex: ["1020 1025 1", "1020 1025 2", "1020 1025 3", "1020 1025 4", "1020 1025 5", "1020 1025 6", "1020 1025 7", "1025 1030 8", "1025 1030 9", "1025 1030 10", "1025 1030 11", "1025 1030 12", "1025 1030 13", "1025 1030 14", "1030 1035 15", "1030 1035 16", "1030 1035 17", "1030 1035 18", "1030 1035 19", "1030 1035 20", "1030 1035 21"]
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        uses: actions/setup-node@v4
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
        with:
          node-version: 18
      - name: Test Code
        uses: mujo-code/puppeteer-headful@16.6.0
        env:
          RANGE_INDEX: ${{ matrix.rangeIndex }}
          MY_DATA: ${{secrets.WK_U}} ${{secrets.WK_I}} ${{secrets.WK_S}} ${{secrets.BK_U}}
        with:
          args: |
            npm run start
      - name: done
        run: exit
