

name: Runme

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        rangeIndex: ["600 605 1", "600 605 2", "600 605 3", "600 605 4", "600 605 5", "600 605 6", "600 605 7", "605 610 8", "605 610 9", "605 610 10", "605 610 11", "605 610 12", "605 610 13", "605 610 14", "610 615 15", "610 615 16", "610 615 17", "610 615 18", "610 615 19", "610 615 20", "610 615 21"]
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        uses: actions/setup-node@v4
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
        with:
          node-version: 18
      - name: Test Code
        uses: mujo-code/puppeteer-headful@16.6.0
        env:
          RANGE_INDEX: ${{ matrix.rangeIndex }}
          MY_DATA: ${{secrets.WK_U}} ${{secrets.WK_I}} ${{secrets.WK_S}} ${{secrets.BK_U}}
        with:
          args: |
            npm run start
      - name: done
        run: exit
