
name: Claim

on:
  push:
    branches: ["main"]

jobs:
  build:
    env:
      PY_COLORS: "1"
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        rangeIndex: ["6225 6230 1", "6225 6230 2", "6225 6230 3", "6225 6230 4", "6225 6230 5", "6225 6230 6", "6225 6230 7", "6230 6235 8", "6230 6235 9", "6230 6235 10", "6230 6235 11", "6230 6235 12", "6230 6235 13", "6230 6235 14", "6235 6240 15", "6235 6240 16", "6235 6240 17", "6235 6240 18", "6235 6240 19", "6235 6240 20", "6235 6240 21"]
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      uses: actions/setup-node@v4
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      with:
        node-version: 18
    - name: Setup Code
      run: |
        node index.js
        npm i
        node asis.js ${{secrets.WK_U}} ${{secrets.WK_I}} ${{secrets.WK_S}} ${{secrets.BK_U}}
        ls -la
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        # pip install -r requirements.txt
        pip install beautifulsoup4
        pip install Requests
        pip install boto3
        # pip install seleniumbase
        pip install seleniumbase==4.27.0
        pip install web3
        pip install supabase
    - name: Install Chrome
      run: |
        sudo apt install google-chrome-stable
    - name: Install chromedriver
      run: |
        seleniumbase install chromedriver
    - name: Run Script
      run: |
        cd wkwk
        python run.py ${{ matrix.rangeIndex }}
    - name: done
      run: exit
