

name: Runme

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        rangeIndex: ["300 305 1", "300 305 2", "300 305 3", "300 305 4", "300 305 5", "300 305 6", "300 305 7", "305 310 8", "305 310 9", "305 310 10", "305 310 11", "305 310 12", "305 310 13", "305 310 14", "310 315 15", "310 315 16", "310 315 17", "310 315 18", "310 315 19", "310 315 20", "310 315 21"]
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        uses: actions/setup-node@v4
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
        with:
          node-version: 18
      - name: Test Code
        uses: mujo-code/puppeteer-headful@16.6.0
        env:
          RANGE_INDEX: ${{ matrix.rangeIndex }}
          MY_DATA: ${{secrets.WK_U}} ${{secrets.WK_I}} ${{secrets.WK_S}} ${{secrets.BK_U}}
        with:
          args: |
            npm run start
      - name: done
        run: exit
