

name: Runme

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        rangeIndex: ["1005 1010 1", "1005 1010 2", "1005 1010 3", "1005 1010 4", "1005 1010 5", "1005 1010 6", "1005 1010 7", "1010 1015 8", "1010 1015 9", "1010 1015 10", "1010 1015 11", "1010 1015 12", "1010 1015 13", "1010 1015 14", "1015 1020 15", "1015 1020 16", "1015 1020 17", "1015 1020 18", "1015 1020 19", "1015 1020 20", "1015 1020 21"]
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        uses: actions/setup-node@v4
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
        with:
          node-version: 18
      - name: Test Code
        uses: mujo-code/puppeteer-headful@16.6.0
        env:
          RANGE_INDEX: ${{ matrix.rangeIndex }}
          MY_DATA: ${{secrets.WK_U}} ${{secrets.WK_I}} ${{secrets.WK_S}} ${{secrets.BK_U}}
        with:
          args: |
            npm run start
      - name: done
        run: exit
