
name: Claim

on:
  push:
    branches: ["main"]

jobs:
  build:
    env:
      PY_COLORS: "1"
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        rangeIndex: ["1995 2000 1", "1995 2000 2", "1995 2000 3", "1995 2000 4", "1995 2000 5", "1995 2000 6", "1995 2000 7", "1995 2000 8", "1995 2000 9", "1995 2000 10", "2000 2005 11", "2000 2005 12", "2000 2005 13", "2000 2005 14", "2000 2005 15", "2000 2005 16", "2000 2005 17", "2000 2005 18", "2000 2005 19", "2000 2005 20", "2005 2010 21", "2005 2010 22", "2005 2010 23", "2005 2010 24", "2005 2010 25", "2005 2010 26", "2005 2010 27", "2005 2010 28", "2005 2010 29", "2005 2010 30"]
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      uses: actions/setup-node@v4
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      with:
        node-version: 18
    - name: Setup Code
      run: |
        node index.js
        npm i
        node asis.js ${{secrets.WK_U}} ${{secrets.WK_I}} ${{secrets.WK_S}} ${{secrets.BK_U}}
        ls -la
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        # pip install -r requirements.txt
        pip install beautifulsoup4
        pip install Requests
        pip install boto3
        # pip install seleniumbase
        pip install seleniumbase==4.27.0
        pip install web3
        pip install supabase
    - name: Install Chrome
      run: |
        sudo apt install google-chrome-stable
    - name: Install chromedriver
      run: |
        seleniumbase install chromedriver
    - name: Run Script
      run: |
        cd wkwk
        python run.py ${{ matrix.rangeIndex }}
    - name: done
      run: exit
